version: "3"

services:
  app:
    build: .
    image: hexletcomponents/devops-example-app
    environment:
      SERVER_MESSAGE: "Hello, this is self study from Hexlet!"

  caddy:
    build:
      context: .
      dockerfile: services/caddy/Dockerfile
    image: hexletcomponents/devops-example-caddy
